spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mhis_db}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
      leak-detection-threshold: 60000

    jpa:
      show-sql: false
      hibernate:
        ddl-auto: validate

logging:
  level:
    com.niyiment.mhis: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN

  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30

server:
  port: ${PORT:8080}